<?php

return [
    'User' => [
        ['name_en' => 'List', 'name_mm' => 'စရင်း', 'slug' => 'users-index'],
        ['name_en' => 'Create', 'name_mm' => 'ပြုလုပ်ရန်', 'slug' => 'users-create'],
        ['name_en' => 'Store', 'name_mm' => 'သိမ်းဆည်းရန်', 'slug' => 'users-store'],
        ['name_en' => 'Edit', 'name_mm' => 'ပြုပြင်ရန်', 'slug' => 'users-edit'],
        ['name_en' => 'Show', 'name_mm' => 'ကြည့်ရန်', 'slug' => 'users-shoe'],
        ['name_en' => 'Update', 'name_mm' => 'ပြန်လည် သိမ်းဆည်းရန်', 'slug' => 'users-update'],
        ['name_en' => 'Delete', 'name_mm' => 'ဖြတ်သိမ်းရန်', 'slug' => 'users-destroy'],
    ],
    'Permission' => [
        ['name_en' => 'List', 'name_mm' => 'အဆင့် စရင်း', 'slug' => 'permissions-index'],
        ['name_en' => 'Create', 'name_mm' => 'အဆင့် ပြုလုပ်ရန်', 'slug' => 'permissions-create'],
        ['name_en' => 'Store', 'name_mm' => 'အဆင့် သိမ်းဆည်းရန်', 'slug' => 'permissions-store'],
        ['name_en' => 'Edit', 'name_mm' => 'အဆင့် ပြုပြင်ရန်', 'slug' => 'permissions-edit'],
        ['name_en' => 'Update', 'name_mm' => 'အဆင့် ပြန်လည် သိမ်းဆည်းရန်', 'slug' => 'permissions-update'],
        ['name_en' => 'Delete', 'name_mm' => 'အဆင့် ဖြတ်သိမ်းရန်', 'slug' => 'permissions-destroy'],
    ],
    'Role' => [
        ['name_en' => 'List', 'name_mm' => 'စရင်း', 'slug' => 'roles-index'],
        ['name_en' => 'Create', 'name_mm' => 'ပြုလုပ်ရန်', 'slug' => 'roles-create'],
        ['name_en' => 'Store', 'name_mm' => 'သိမ်းဆည်းရန်', 'slug' => 'roles-store'],
        ['name_en' => 'Edit', 'name_mm' => 'ပြုပြင်ရန်', 'slug' => 'roles-edit'],
        ['name_en' => 'Update', 'name_mm' => 'ပြန်လည် သိမ်းဆည်းရန်', 'slug' => 'roles-update'],
        ['name_en' => 'Delete', 'name_mm' => 'ဖြတ်သိမ်းရန်', 'slug' => 'roles-destroy'],
    ],
    'Role-Permissions-Assign' => [
        ['name_en' => 'Assign List', 'name_mm' => 'ချိတ်ဆက် စရင်း', 'slug' => 'assigns-permissions-index'],
        ['name_en' => 'Assign Create', 'name_mm' => 'ချိတ်ဆက်တာ ကို ပြုလုပ်ရန်', 'slug' => 'assigns-permissions-create'],
        ['name_en' => 'Assign Store', 'name_mm' => 'ချိတ်ဆက်တာ ကို သိမ်းဆည်းရန်', 'slug' => 'assigns-permissions-store'],
        ['name_en' => 'Assign Edit', 'name_mm' => 'ချိတ်ဆက်တာ ကို ပြုပြင်ရန်', 'slug' => 'assigns-permissions-edit'],
        ['name_en' => 'Assign Update', 'name_mm' => 'ချိတ်ဆက်တာ ကို ပြန်လည် သိမ်းဆည်းရန်', 'slug' => 'assigns-permissions-update'],
        ['name_en' => 'Assign Delete', 'name_mm' => 'ချိတ်ဆက်တာ ကို ဖြတ်သိမ်းရန်', 'slug' => 'assigns-permissions-destroy'],
    ],
    'Category' => [
        ['name_en' => 'List', 'name_mm' => 'စရင်း', 'slug' => 'categories-index'],
        ['name_en' => 'Create', 'name_mm' => 'ပြုလုပ်ရန်', 'slug' => 'categories-create'],
        ['name_en' => 'Store', 'name_mm' => 'သိမ်းဆည်းရန်', 'slug' => 'categories-store'],
        ['name_en' => 'Edit', 'name_mm' => 'ပြုပြင်ရန်', 'slug' => 'categories-edit'],
        ['name_en' => 'Update', 'name_mm' => 'ပြန်လည် သိမ်းဆည်းရန်', 'slug' => 'categories-update'],
        ['name_en' => 'Destroy', 'name_mm' => 'ဖြတ်သိမ်းရန်', 'slug' => 'categories-destroy'],
        ['name_en' => 'To Trash', 'name_mm' => 'ခဏ ဖြတ်သိမ်းရန်', 'slug' => 'categories-to-trash'],
        ['name_en' => 'Trashed List', 'name_mm' => 'ခဏ ဖြတ်သိမ်းစရင်း', 'slug' => 'categories-trashed'],
        ['name_en' => 'Restore', 'name_mm' => 'ခဏ ဖြတ်သိမ်းရာမှာ ပြန်ယူရန်', 'slug' => 'categories-restore'],
        ['name_en' => 'Restore All', 'name_mm' => 'ခဏ ဖြတ်သိမ်းရာမှာ ပြန်ယူရန်', 'slug' => 'categories-restore-all'],
    ],
    'SubCategory' => [
        ['name_en' => 'List', 'name_mm' => 'စရင်း', 'slug' => 'subcategories-index'],
        ['name_en' => 'Create', 'name_mm' => 'ပြုလုပ်ရန်', 'slug' => 'subcategories-create'],
        ['name_en' => 'Store', 'name_mm' => 'သိမ်းဆည်းရန်', 'slug' => 'subcategories-store'],
        ['name_en' => 'Edit', 'name_mm' => 'ပြုပြင်ရန်', 'slug' => 'subcategories-edit'],
        ['name_en' => 'Update', 'name_mm' => 'ပြန်လည် သိမ်းဆည်းရန်', 'slug' => 'subcategories-update'],
        ['name_en' => 'Destroy', 'name_mm' => 'ဖြတ်သိမ်းရန်', 'slug' => 'subcategories-destroy'],
        ['name_en' => 'To Trash', 'name_mm' => 'ခဏ ဖြတ်သိမ်းရန်', 'slug' => 'subcategories-to-trash'],
        ['name_en' => 'Trashed List', 'name_mm' => 'ခဏ ဖြတ်သိမ်းစရင်း', 'slug' => 'subcategories-trashed'],
        ['name_en' => 'Restore', 'name_mm' => 'ခဏ ဖြတ်သိမ်းရာမှာ ပြန်ယူရန်', 'slug' => 'subcategories-restore'],
        ['name_en' => 'Restore All', 'name_mm' => 'ခဏ ဖြတ်သိမ်းရာမှာ ပြန်ယူရန်', 'slug' => 'subcategories-restore-all'],
    ],
    'Brand' => [
        ['name_en' => 'List', 'name_mm' => 'စရင်း', 'slug' => 'brands-index'],
        ['name_en' => 'Create', 'name_mm' => 'ပြုလုပ်ရန်', 'slug' => 'brands-create'],
        ['name_en' => 'Store', 'name_mm' => 'သိမ်းဆည်းရန်', 'slug' => 'brands-store'],
        ['name_en' => 'Edit', 'name_mm' => 'ပြုပြင်ရန်', 'slug' => 'brands-edit'],
        ['name_en' => 'Update', 'name_mm' => 'ပြန်လည် သိမ်းဆည်းရန်', 'slug' => 'brands-update'],
        ['name_en' => 'Destroy', 'name_mm' => 'ဖြတ်သိမ်းရန်', 'slug' => 'brands-destroy'],
        ['name_en' => 'To Trash', 'name_mm' => 'ခဏ ဖြတ်သိမ်းရန်', 'slug' => 'brands-to-trash'],
        ['name_en' => 'Trashed List', 'name_mm' => 'ခဏ ဖြတ်သိမ်းစရင်း', 'slug' => 'brands-trashed'],
        ['name_en' => 'Restore', 'name_mm' => 'ခဏ ဖြတ်သိမ်းရာမှာ ပြန်ယူရန်', 'slug' => 'brands-restore'],
        ['name_en' => 'Restore All', 'name_mm' => 'ခဏ ဖြတ်သိမ်းရာမှာ ပြန်ယူရန်', 'slug' => 'brands-restore-all'],
    ],
    'Category-Brands-Assign' => [
        ['name_en' => 'Assign List', 'name_mm' => 'ချိတ်ဆက် စရင်း', 'slug' => 'assigns-categories-index'],
        ['name_en' => 'Assign Create', 'name_mm' => 'ချိတ်ဆက်တာ ကို ပြုလုပ်ရန်', 'slug' => 'assigns-categories-create'],
        ['name_en' => 'Assign Store', 'name_mm' => 'ချိတ်ဆက်တာ ကို သိမ်းဆည်းရန်', 'slug' => 'assigns-categories-store'],
        ['name_en' => 'Assign Edit', 'name_mm' => 'ချိတ်ဆက်တာ ကို ပြုပြင်ရန်', 'slug' => 'assigns-categories-edit'],
        ['name_en' => 'Assign Update', 'name_mm' => 'ချိတ်ဆက်တာ ကို ပြန်လည် သိမ်းဆည်းရန်', 'slug' => 'assigns-categories-update'],
        ['name_en' => 'Assign Destroy', 'name_mm' => 'ချိတ်ဆက်တာ ကို ဖြတ်သိမ်းရန်', 'slug' => 'assigns-categories-destroy'],
    ],
    'Payment' => [
        ['name_en' => 'List', 'name_mm' => 'စရင်း', 'slug' => 'payments-index'],
        ['name_en' => 'Create', 'name_mm' => 'ပြုလုပ်ရန်', 'slug' => 'payments-create'],
        ['name_en' => 'Store', 'name_mm' => 'သိမ်းဆည်းရန်', 'slug' => 'payments-store'],
        ['name_en' => 'Edit', 'name_mm' => 'ပြုပြင်ရန်', 'slug' => 'payments-edit'],
        ['name_en' => 'Update', 'name_mm' => 'ပြန်လည် သိမ်းဆည်းရန်', 'slug' => 'payments-update'],
        ['name_en' => 'Destroy', 'name_mm' => 'ဖြတ်သိမ်းရန်', 'slug' => 'payments-destroy'],
        ['name_en' => 'To Trash', 'name_mm' => 'ခဏ ဖြတ်သိမ်းရန်', 'slug' => 'payments-to-trash'],
        ['name_en' => 'Trashed List', 'name_mm' => 'ခဏ ဖြတ်သိမ်းစရင်း', 'slug' => 'payments-trashed'],
        ['name_en' => 'Restore', 'name_mm' => 'ခဏ ဖြတ်သိမ်းရာမှာ ပြန်ယူရန်', 'slug' => 'payments-restore'],
        ['name_en' => 'Restore All', 'name_mm' => 'ခဏ ဖြတ်သိမ်းရာမှာ ပြန်ယူရန်', 'slug' => 'payments-restore-all'],
    ],
    'Color' => [
        ['name_en' => 'List', 'name_mm' => 'စရင်း', 'slug' => 'colors-index'],
        ['name_en' => 'Create', 'name_mm' => 'ပြုလုပ်ရန်', 'slug' => 'colors-create'],
        ['name_en' => 'Store', 'name_mm' => 'သိမ်းဆည်းရန်', 'slug' => 'colors-store'],
        ['name_en' => 'Edit', 'name_mm' => 'ပြုပြင်ရန်', 'slug' => 'colors-edit'],
        ['name_en' => 'Update', 'name_mm' => 'ပြန်လည် သိမ်းဆည်းရန်', 'slug' => 'colors-update'],
        ['name_en' => 'Destroy', 'name_mm' => 'ဖြတ်သိမ်းရန်', 'slug' => 'colors-destroy'],
        ['name_en' => 'To Trash', 'name_mm' => 'ခဏ ဖြတ်သိမ်းရန်', 'slug' => 'colors-to-trash'],
        ['name_en' => 'Trashed List', 'name_mm' => 'ခဏ ဖြတ်သိမ်းစရင်း', 'slug' => 'colors-trashed'],
        ['name_en' => 'Restore', 'name_mm' => 'ခဏ ဖြတ်သိမ်းရာမှာ ပြန်ယူရန်', 'slug' => 'colors-restore'],
        ['name_en' => 'Restore All', 'name_mm' => 'ခဏ ဖြတ်သိမ်းရာမှာ ပြန်ယူရန်', 'slug' => 'colors-restore-all'],
    ],
    'Size' => [
        ['name_en' => 'List', 'name_mm' => 'စရင်း', 'slug' => 'sizes-index'],
        ['name_en' => 'Create', 'name_mm' => 'ပြုလုပ်ရန်', 'slug' => 'sizes-create'],
        ['name_en' => 'Store', 'name_mm' => 'သိမ်းဆည်းရန်', 'slug' => 'sizes-store'],
        ['name_en' => 'Edit', 'name_mm' => 'ပြုပြင်ရန်', 'slug' => 'sizes-edit'],
        ['name_en' => 'Update', 'name_mm' => 'ပြန်လည် သိမ်းဆည်းရန်', 'slug' => 'sizes-update'],
        ['name_en' => 'Destroy', 'name_mm' => 'ဖြတ်သိမ်းရန်', 'slug' => 'sizes-destroy'],
        ['name_en' => 'To Trash', 'name_mm' => 'ခဏ ဖြတ်သိမ်းရန်', 'slug' => 'sizes-to-trash'],
        ['name_en' => 'Trashed List', 'name_mm' => 'ခဏ ဖြတ်သိမ်းစရင်း', 'slug' => 'sizes-trashed'],
        ['name_en' => 'Restore', 'name_mm' => 'ခဏ ဖြတ်သိမ်းရာမှာ ပြန်ယူရန်', 'slug' => 'sizes-restore'],
        ['name_en' => 'Restore All', 'name_mm' => 'ခဏ ဖြတ်သိမ်းရာမှာ ပြန်ယူရန်', 'slug' => 'sizes-restore-all'],
    ],
    'Product' => [
        ['name_en' => 'List', 'name_mm' => 'စရင်း', 'slug' => 'products-index'],
        ['name_en' => 'Create', 'name_mm' => 'ပြုလုပ်ရန်', 'slug' => 'products-create'],
        ['name_en' => 'Store', 'name_mm' => 'သိမ်းဆည်းရန်', 'slug' => 'products-store'],
        ['name_en' => 'Edit', 'name_mm' => 'ပြုပြင်ရန်', 'slug' => 'products-edit'],
        ['name_en' => 'Show', 'name_mm' => 'ကြည့်ရန်', 'slug' => 'products-show'],
        ['name_en' => 'Update', 'name_mm' => 'ပြန်လည် သိမ်းဆည်းရန်', 'slug' => 'products-update'],
        ['name_en' => 'Destroy', 'name_mm' => 'ဖြတ်သိမ်းရန်', 'slug' => 'products-destroy'],
        ['name_en' => 'To Trash', 'name_mm' => 'ခဏ ဖြတ်သိမ်းရန်', 'slug' => 'products-to-trash'],
        ['name_en' => 'Trashed List', 'name_mm' => 'ခဏ ဖြတ်သိမ်းစရင်း', 'slug' => 'products-trashed'],
        ['name_en' => 'Restore', 'name_mm' => 'ခဏ ဖြတ်သိမ်းရာမှာ ပြန်ယူရန်', 'slug' => 'products-restore'],
        ['name_en' => 'Restore All', 'name_mm' => 'ခဏ ဖြတ်သိမ်းရာမှာ ပြန်ယူရန်', 'slug' => 'products-restore-all'],
    ],
    'Product-Attribute' => [
        ['name_en' => 'List With Product', 'name_mm' => 'ကုန်ပစ္စည်း နှင့်ပတ်သက်သော အချက်အလက် စရင်း', 'slug' => 'attributes-product'],
        ['name_en' => 'List', 'name_mm' => 'စရင်း', 'slug' => 'attributes-index'],
        ['name_en' => 'Create', 'name_mm' => 'ပြုလုပ်ရန်', 'slug' => 'attributes-create'],
        ['name_en' => 'Create', 'name_mm' => 'ပြုလုပ်ရန်', 'slug' => 'attributes-create'],
        ['name_en' => 'Store', 'name_mm' => 'သိမ်းဆည်းရန်', 'slug' => 'attributes-store'],
        ['name_en' => 'Edit', 'name_mm' => 'ပြုပြင်ရန်', 'slug' => 'attributes-edit'],
        ['name_en' => 'Show', 'name_mm' => 'ကြည့်ရန်', 'slug' => 'attributes-show'],
        ['name_en' => 'Update', 'name_mm' => 'ပြန်လည် သိမ်းဆည်းရန်', 'slug' => 'attributes-update'],
        ['name_en' => 'Destroy', 'name_mm' => 'ဖြတ်သိမ်းရန်', 'slug' => 'attributes-destroy'],
        ['name_en' => 'To Trash', 'name_mm' => 'ခဏ ဖြတ်သိမ်းရန်', 'slug' => 'attributes-to-trash'],
        ['name_en' => 'Trashed List', 'name_mm' => 'ခဏ ဖြတ်သိမ်းစရင်း', 'slug' => 'attributes-trashed'],
        ['name_en' => 'Restore', 'name_mm' => 'ခဏ ဖြတ်သိမ်းရာမှာ ပြန်ယူရန်', 'slug' => 'attributes-restore'],
        ['name_en' => 'Restore All', 'name_mm' => 'ခဏ ဖြတ်သိမ်းရာမှာ ပြန်ယူရန်', 'slug' => 'attributes-restore-all'],
    ],
];

// <?php

// return [
//     'User' => [
//         ['name_en' => 'User List', 'name_mm' => 'အသုံးပြုသူ စရင်း', 'slug' => 'users-index'],
//         ['name_en' => 'User Create', 'name_mm' => 'အသုံးပြုသူ ကို ပြုလုပ်ရန်', 'slug' => 'users-create'],
//         ['name_en' => 'User Store', 'name_mm' => 'အသုံးပြုသူ ကို သိမ်းဆည်းရန်', 'slug' => 'users-store'],
//         ['name_en' => 'User Edit', 'name_mm' => 'အသုံးပြုသူ ကို ပြုပြင်ရန်', 'slug' => 'users-edit'],
//         ['name_en' => 'User Show', 'name_mm' => 'အသုံးပြုသူ ကို ကြည့်ရန်', 'slug' => 'users-shoe'],
//         ['name_en' => 'User Update', 'name_mm' => 'အသုံးပြုသူ ကို ပြန်လည် သိမ်းဆည်းရန်', 'slug' => 'users-update'],
//         ['name_en' => 'User Delete', 'name_mm' => 'အသုံးပြုသူ ကို ဖြတ်သိမ်းရန်', 'slug' => 'users-destroy'],
//     ],
//     'Permission' => [
//         ['name_en' => 'Permission List', 'name_mm' => 'အသုံးပြုသူ၏ အဆင့် စရင်း', 'slug' => 'permissions-index'],
//         ['name_en' => 'Permission Create', 'name_mm' => 'အသုံးပြုသူ၏ အဆင့် ပြုလုပ်ရန်', 'slug' => 'permissions-create'],
//         ['name_en' => 'Permission Store', 'name_mm' => 'အသုံးပြုသူ၏ အဆင့် သိမ်းဆည်းရန်', 'slug' => 'permissions-store'],
//         ['name_en' => 'Permission Edit', 'name_mm' => 'အသုံးပြုသူ၏ အဆင့် ပြုပြင်ရန်', 'slug' => 'permissions-edit'],
//         ['name_en' => 'Permission Update', 'name_mm' => 'အသုံးပြုသူ၏ အဆင့် ပြန်လည် သိမ်းဆည်းရန်', 'slug' => 'permissions-update'],
//         ['name_en' => 'Permission Delete', 'name_mm' => 'အသုံးပြုသူ၏ အဆင့် ဖြတ်သိမ်းရန်', 'slug' => 'permissions-destroy'],
//     ],
//     'Role' => [
//         ['name_en' => 'Role List', 'name_mm' => 'အသုံးပြုခွင့် စရင်း', 'slug' => 'roles-index'],
//         ['name_en' => 'Role Create', 'name_mm' => 'အသုံးပြုခွင့် ပြုလုပ်ရန်', 'slug' => 'roles-create'],
//         ['name_en' => 'Role Store', 'name_mm' => 'အသုံးပြုခွင့် သိမ်းဆည်းရန်', 'slug' => 'roles-store'],
//         ['name_en' => 'Role Edit', 'name_mm' => 'အသုံးပြုခွင့် ပြုပြင်ရန်', 'slug' => 'roles-edit'],
//         ['name_en' => 'Role Update', 'name_mm' => 'အသုံးပြုခွင့် ပြန်လည် သိမ်းဆည်းရန်', 'slug' => 'roles-update'],
//         ['name_en' => 'Role Delete', 'name_mm' => 'အသုံးပြုခွင့် ဖြတ်သိမ်းရန်', 'slug' => 'roles-destroy'],
//     ],
//     'Role-Permissions-Assign' => [
//         ['name_en' => 'Permission & Role Assign List', 'name_mm' => 'အသုံးပြုခွင့် နှင့် အဆင့် ချိတ်ဆက် စရင်း', 'slug' => 'assigns-permissions-index'],
//         ['name_en' => 'Permission & Role Assign Create', 'name_mm' => 'အသုံးပြုခွင့် နှင့် အဆင့် ချိတ်ဆက်တာ ကို ပြုလုပ်ရန်', 'slug' => 'assigns-permissions-create'],
//         ['name_en' => 'Permission & Role Assign Store', 'name_mm' => 'အသုံးပြုခွင့် နှင့် အဆင့် ချိတ်ဆက်တာ ကို သိမ်းဆည်းရန်', 'slug' => 'assigns-permissions-store'],
//         ['name_en' => 'Permission & Role Assign Edit', 'name_mm' => 'အသုံးပြုခွင့် နှင့် အဆင့် ချိတ်ဆက်တာ ကို ပြုပြင်ရန်', 'slug' => 'assigns-permissions-edit'],
//         ['name_en' => 'Permission & Role Assign Update', 'name_mm' => 'အသုံးပြုခွင့် နှင့် အဆင့် ချိတ်ဆက်တာ ကို ပြန်လည် သိမ်းဆည်းရန်', 'slug' => 'assigns-permissions-update'],
//         ['name_en' => 'Permission & Role Assign Delete', 'name_mm' => 'အသုံးပြုခွင့် နှင့် အဆင့် ချိတ်ဆက်တာ ကို ဖြတ်သိမ်းရန်', 'slug' => 'assigns-permissions-destroy'],
//     ],
//     'Category' => [
//         ['name_en' => 'Category List', 'name_mm' => 'ကုန်ပစ္စည်း အမျိုးအစား စရင်း', 'slug' => 'categories-index'],
//         ['name_en' => 'Category Create', 'name_mm' => 'ကုန်ပစ္စည်း အမျိုးအစား ကို ပြုလုပ်ရန်', 'slug' => 'categories-create'],
//         ['name_en' => 'Category Store', 'name_mm' => 'ကုန်ပစ္စည်း အမျိုးအစား ကို သိမ်းဆည်းရန်', 'slug' => 'categories-store'],
//         ['name_en' => 'Category Edit', 'name_mm' => 'ကုန်ပစ္စည်း အမျိုးအစား ကို ပြုပြင်ရန်', 'slug' => 'categories-edit'],
//         ['name_en' => 'Category Update', 'name_mm' => 'ကုန်ပစ္စည်း အမျိုးအစား ကို ပြန်လည် သိမ်းဆည်းရန်', 'slug' => 'categories-update'],
//         ['name_en' => 'Category Destroy', 'name_mm' => 'ကုန်ပစ္စည်း အမျိုးအစား ကို ဖြတ်သိမ်းရန်', 'slug' => 'categories-destroy'],
//         ['name_en' => 'Category To Trash', 'name_mm' => 'ကုန်ပစ္စည်း အမျိုးအစား ကို ခဏ ဖြတ်သိမ်းရန်', 'slug' => 'categories-to-trash'],
//         ['name_en' => 'Category Trashed List', 'name_mm' => 'ကုန်ပစ္စည်း အမျိုးအစား ကို ခဏ ဖြတ်သိမ်းစရင်း', 'slug' => 'categories-trashed'],
//         ['name_en' => 'Category Restore', 'name_mm' => 'ကုန်ပစ္စည်း အမျိုးအစား ကို ခဏ ဖြတ်သိမ်းရာမှာ ပြန်ယူရန်', 'slug' => 'categories-restore'],
//         ['name_en' => 'Category Restore All', 'name_mm' => 'ကုန်ပစ္စည်း အမျိုးအစားများ ကို ခဏ ဖြတ်သိမ်းရာမှာ ပြန်ယူရန်', 'slug' => 'categories-restore-all'],
//     ],
//     'SubCategory' => [
//         ['name_en' => 'Sub-Category List', 'name_mm' => 'ကုန်ပစ္စည်း အမျိုးအစားခွဲ စရင်း', 'slug' => 'subcategories-index'],
//         ['name_en' => 'Sub-Category Create', 'name_mm' => 'ကုန်ပစ္စည်း အမျိုးအစားခွဲ ကို ပြုလုပ်ရန်', 'slug' => 'subcategories-create'],
//         ['name_en' => 'Sub-Category Store', 'name_mm' => 'ကုန်ပစ္စည်း အမျိုးအစားခွဲ ကို သိမ်းဆည်းရန်', 'slug' => 'subcategories-store'],
//         ['name_en' => 'Sub-Category Edit', 'name_mm' => 'ကုန်ပစ္စည်း အမျိုးအစားခွဲ ကို ပြုပြင်ရန်', 'slug' => 'subcategories-edit'],
//         ['name_en' => 'Sub-Category Update', 'name_mm' => 'ကုန်ပစ္စည်း အမျိုးအစားခွဲ ကို ပြန်လည် သိမ်းဆည်းရန်', 'slug' => 'subcategories-update'],
//         ['name_en' => 'Sub-Category Destroy', 'name_mm' => 'ကုန်ပစ္စည်း အမျိုးအစားခွဲ ကို ဖြတ်သိမ်းရန်', 'slug' => 'subcategories-destroy'],
//         ['name_en' => 'Sub-Category To Trash', 'name_mm' => 'ကုန်ပစ္စည်း အမျိုးအစားခွဲ ကို ခဏ ဖြတ်သိမ်းရန်', 'slug' => 'subcategories-to-trash'],
//         ['name_en' => 'Sub-Category Trashed List', 'name_mm' => 'ကုန်ပစ္စည်း အမျိုးအစားခွဲ ကို ခဏ ဖြတ်သိမ်းစရင်း', 'slug' => 'subcategories-trashed'],
//         ['name_en' => 'Sub-Category Restore', 'name_mm' => 'ကုန်ပစ္စည်း အမျိုးအစားခွဲ ကို ခဏ ဖြတ်သိမ်းရာမှာ ပြန်ယူရန်', 'slug' => 'subcategories-restore'],
//         ['name_en' => 'Sub-Category Restore All', 'name_mm' => 'ကုန်ပစ္စည်း အမျိုးအစားခွဲများ ကို ခဏ ဖြတ်သိမ်းရာမှာ ပြန်ယူရန်', 'slug' => 'subcategories-restore-all'],
//     ],
//     'Brand' => [
//         ['name_en' => 'Brand List', 'name_mm' => 'ကုန်အမှတ်တံဆိပ် စရင်း', 'slug' => 'brands-index'],
//         ['name_en' => 'Brand Create', 'name_mm' => 'ကုန်အမှတ်တံဆိပ် ကို ပြုလုပ်ရန်', 'slug' => 'brands-create'],
//         ['name_en' => 'Brand Store', 'name_mm' => 'ကုန်အမှတ်တံဆိပ် ကို သိမ်းဆည်းရန်', 'slug' => 'brands-store'],
//         ['name_en' => 'Brand Edit', 'name_mm' => 'ကုန်အမှတ်တံဆိပ် ကို ပြုပြင်ရန်', 'slug' => 'brands-edit'],
//         ['name_en' => 'Brand Update', 'name_mm' => 'ကုန်အမှတ်တံဆိပ် ကို ပြန်လည် သိမ်းဆည်းရန်', 'slug' => 'brands-update'],
//         ['name_en' => 'Brand Destroy', 'name_mm' => 'ကုန်အမှတ်တံဆိပ် ကို ဖြတ်သိမ်းရန်', 'slug' => 'brands-destroy'],
//         ['name_en' => 'Brand To Trash', 'name_mm' => 'ကုန်အမှတ်တံဆိပ် ကို ခဏ ဖြတ်သိမ်းရန်', 'slug' => 'brands-to-trash'],
//         ['name_en' => 'Brand Trashed List', 'name_mm' => 'ကုန်အမှတ်တံဆိပ် ကို ခဏ ဖြတ်သိမ်းစရင်း', 'slug' => 'brands-trashed'],
//         ['name_en' => 'Brand Restore', 'name_mm' => 'ကုန်အမှတ်တံဆိပ် ကို ခဏ ဖြတ်သိမ်းရာမှာ ပြန်ယူရန်', 'slug' => 'brands-restore'],
//         ['name_en' => 'Brand Restore All', 'name_mm' => 'ကုန်အမှတ်တံဆိပ်များ ကို ခဏ ဖြတ်သိမ်းရာမှာ ပြန်ယူရန်', 'slug' => 'brands-restore-all'],
//     ],
//     'Category-Brands-Assign' => [
//         ['name_en' => 'Category & Brand Assign List', 'name_mm' => 'ကုန်ပစ္စည်း အမျိုးအစား နှင့် ကုန်အမှတ်တံဆိပ် ချိတ်ဆက် စရင်း', 'slug' => 'assigns-categories-index'],
//         ['name_en' => 'Category & Brand Assign Create', 'name_mm' => 'ကုန်ပစ္စည်း အမျိုးအစား နှင့် ကုန်အမှတ်တံဆိပ် ချိတ်ဆက်တာ ကို ပြုလုပ်ရန်', 'slug' => 'assigns-categories-create'],
//         ['name_en' => 'Category & Brand Assign Store', 'name_mm' => 'ကုန်ပစ္စည်း အမျိုးအစား နှင့် ကုန်အမှတ်တံဆိပ် ချိတ်ဆက်တာ ကို သိမ်းဆည်းရန်', 'slug' => 'assigns-categories-store'],
//         ['name_en' => 'Category & Brand Assign Edit', 'name_mm' => 'ကုန်ပစ္စည်း အမျိုးအစား နှင့် ကုန်အမှတ်တံဆိပ် ချိတ်ဆက်တာ ကို ပြုပြင်ရန်', 'slug' => 'assigns-categories-edit'],
//         ['name_en' => 'Category & Brand Assign Update', 'name_mm' => 'ကုန်ပစ္စည်း အမျိုးအစား နှင့် ကုန်အမှတ်တံဆိပ် ချိတ်ဆက်တာ ကို ပြန်လည် သိမ်းဆည်းရန်', 'slug' => 'assigns-categories-update'],
//         ['name_en' => 'Category & Brand Assign Destroy', 'name_mm' => 'ကုန်ပစ္စည်း အမျိုးအစား နှင့် ကုန်အမှတ်တံဆိပ် ချိတ်ဆက်တာ ကို ဖြတ်သိမ်းရန်', 'slug' => 'assigns-categories-destroy'],
//     ],
//     'Payment' => [
//         ['name_en' => 'Payment List', 'name_mm' => 'ငွေပေးချေမှုစနစ် စရင်း', 'slug' => 'payments-index'],
//         ['name_en' => 'Payment Create', 'name_mm' => 'ငွေပေးချေမှုစနစ် ကို ပြုလုပ်ရန်', 'slug' => 'payments-create'],
//         ['name_en' => 'Payment Store', 'name_mm' => 'ငွေပေးချေမှုစနစ် ကို သိမ်းဆည်းရန်', 'slug' => 'payments-store'],
//         ['name_en' => 'Payment Edit', 'name_mm' => 'ငွေပေးချေမှုစနစ် ကို ပြုပြင်ရန်', 'slug' => 'payments-edit'],
//         ['name_en' => 'Payment Update', 'name_mm' => 'ငွေပေးချေမှုစနစ် ကို ပြန်လည် သိမ်းဆည်းရန်', 'slug' => 'payments-update'],
//         ['name_en' => 'Payment Destroy', 'name_mm' => 'ငွေပေးချေမှုစနစ် ကို ဖြတ်သိမ်းရန်', 'slug' => 'payments-destroy'],
//         ['name_en' => 'Payment To Trash', 'name_mm' => 'ငွေပေးချေမှုစနစ် ကို ခဏ ဖြတ်သိမ်းရန်', 'slug' => 'payments-to-trash'],
//         ['name_en' => 'Payment Trashed List', 'name_mm' => 'ငွေပေးချေမှုစနစ် ကို ခဏ ဖြတ်သိမ်းစရင်း', 'slug' => 'payments-trashed'],
//         ['name_en' => 'Payment Restore', 'name_mm' => 'ငွေပေးချေမှုစနစ် ကို ခဏ ဖြတ်သိမ်းရာမှာ ပြန်ယူရန်', 'slug' => 'payments-restore'],
//         ['name_en' => 'Payment Restore All', 'name_mm' => 'ငွေပေးချေမှုစနစ်များ ကို ခဏ ဖြတ်သိမ်းရာမှာ ပြန်ယူရန်', 'slug' => 'payments-restore-all'],
//     ],
//     'Color' => [
//         ['name_en' => 'Color List', 'name_mm' => 'အရောင် စရင်း', 'slug' => 'colors-index'],
//         ['name_en' => 'Color Create', 'name_mm' => 'အရောင် ကို ပြုလုပ်ရန်', 'slug' => 'colors-create'],
//         ['name_en' => 'Color Store', 'name_mm' => 'အရောင် ကို သိမ်းဆည်းရန်', 'slug' => 'colors-store'],
//         ['name_en' => 'Color Edit', 'name_mm' => 'အရောင် ကို ပြုပြင်ရန်', 'slug' => 'colors-edit'],
//         ['name_en' => 'Color Update', 'name_mm' => 'အရောင် ကို ပြန်လည် သိမ်းဆည်းရန်', 'slug' => 'colors-update'],
//         ['name_en' => 'Color Destroy', 'name_mm' => 'အရောင် ကို ဖြတ်သိမ်းရန်', 'slug' => 'colors-destroy'],
//         ['name_en' => 'Color To Trash', 'name_mm' => 'အရောင် ကို ခဏ ဖြတ်သိမ်းရန်', 'slug' => 'colors-to-trash'],
//         ['name_en' => 'Color Trashed List', 'name_mm' => 'အရောင် ကို ခဏ ဖြတ်သိမ်းစရင်း', 'slug' => 'colors-trashed'],
//         ['name_en' => 'Color Restore', 'name_mm' => 'အရောင် ကို ခဏ ဖြတ်သိမ်းရာမှာ ပြန်ယူရန်', 'slug' => 'colors-restore'],
//         ['name_en' => 'Color Restore All', 'name_mm' => 'အရောင်များ ကို ခဏ ဖြတ်သိမ်းရာမှာ ပြန်ယူရန်', 'slug' => 'colors-restore-all'],
//     ],
//     'Size' => [
//         ['name_en' => 'Size List', 'name_mm' => 'အရွယ်အစား စရင်း', 'slug' => 'sizes-index'],
//         ['name_en' => 'Size Create', 'name_mm' => 'အရွယ်အစား ကို ပြုလုပ်ရန်', 'slug' => 'sizes-create'],
//         ['name_en' => 'Size Store', 'name_mm' => 'အရွယ်အစား ကို သိမ်းဆည်းရန်', 'slug' => 'sizes-store'],
//         ['name_en' => 'Size Edit', 'name_mm' => 'အရွယ်အစား ကို ပြုပြင်ရန်', 'slug' => 'sizes-edit'],
//         ['name_en' => 'Size Update', 'name_mm' => 'အရွယ်အစား ကို ပြန်လည် သိမ်းဆည်းရန်', 'slug' => 'sizes-update'],
//         ['name_en' => 'Size Destroy', 'name_mm' => 'အရွယ်အစား ကို ဖြတ်သိမ်းရန်', 'slug' => 'sizes-destroy'],
//         ['name_en' => 'Size To Trash', 'name_mm' => 'အရွယ်အစား ကို ခဏ ဖြတ်သိမ်းရန်', 'slug' => 'sizes-to-trash'],
//         ['name_en' => 'Size Trashed List', 'name_mm' => 'အရွယ်အစား ကို ခဏ ဖြတ်သိမ်းစရင်း', 'slug' => 'sizes-trashed'],
//         ['name_en' => 'Size Restore', 'name_mm' => 'အရွယ်အစား ကို ခဏ ဖြတ်သိမ်းရာမှာ ပြန်ယူရန်', 'slug' => 'sizes-restore'],
//         ['name_en' => 'Size Restore All', 'name_mm' => 'အရွယ်အစားများ ကို ခဏ ဖြတ်သိမ်းရာမှာ ပြန်ယူရန်', 'slug' => 'sizes-restore-all'],
//     ],
//     'Product' => [
//         ['name_en' => 'Product List', 'name_mm' => 'ကုန်ပစ္စည်း စရင်း', 'slug' => 'products-index'],
//         ['name_en' => 'Product Create', 'name_mm' => 'ကုန်ပစ္စည်း ကို ပြုလုပ်ရန်', 'slug' => 'products-create'],
//         ['name_en' => 'Product Store', 'name_mm' => 'ကုန်ပစ္စည်း ကို သိမ်းဆည်းရန်', 'slug' => 'products-store'],
//         ['name_en' => 'Product Edit', 'name_mm' => 'ကုန်ပစ္စည်း ကို ပြုပြင်ရန်', 'slug' => 'products-edit'],
//         ['name_en' => 'Product Show', 'name_mm' => 'ကုန်ပစ္စည်း ကို ကြည့်ရန်', 'slug' => 'products-show'],
//         ['name_en' => 'Product Update', 'name_mm' => 'ကုန်ပစ္စည်း ကို ပြန်လည် သိမ်းဆည်းရန်', 'slug' => 'products-update'],
//         ['name_en' => 'Product Destroy', 'name_mm' => 'ကုန်ပစ္စည်း ကို ဖြတ်သိမ်းရန်', 'slug' => 'products-destroy'],
//         ['name_en' => 'Product To Trash', 'name_mm' => 'ကုန်ပစ္စည်း ကို ခဏ ဖြတ်သိမ်းရန်', 'slug' => 'products-to-trash'],
//         ['name_en' => 'Product Trashed List', 'name_mm' => 'ကုန်ပစ္စည်း ကို ခဏ ဖြတ်သိမ်းစရင်း', 'slug' => 'products-trashed'],
//         ['name_en' => 'Product Restore', 'name_mm' => 'ကုန်ပစ္စည်း ကို ခဏ ဖြတ်သိမ်းရာမှာ ပြန်ယူရန်', 'slug' => 'products-restore'],
//         ['name_en' => 'Product Restore All', 'name_mm' => 'ကုန်ပစ္စည်းများ ကို ခဏ ဖြတ်သိမ်းရာမှာ ပြန်ယူရန်', 'slug' => 'products-restore-all'],
//     ],
//     'Product-Attribute' => [
//         ['name_en' => 'Product Attribute List With Product', 'name_mm' => 'ကုန်ပစ္စည်း နှင့်ပတ်သက်သော အချက်အလက် စရင်း', 'slug' => 'attributes-product'],
//         ['name_en' => 'Product Attribute List', 'name_mm' => 'ကုန်ပစ္စည်း အချက်အလက် စရင်း', 'slug' => 'attributes-index'],
//         ['name_en' => 'Product Attribute Create', 'name_mm' => 'ကုန်ပစ္စည်း အချက်အလက် ကို ပြုလုပ်ရန်', 'slug' => 'attributes-create'],
//         ['name_en' => 'Product Attribute Create', 'name_mm' => 'ကုန်ပစ္စည်း အချက်အလက် ကို ပြုလုပ်ရန်', 'slug' => 'attributes-create'],
//         ['name_en' => 'Product Attribute Store', 'name_mm' => 'ကုန်ပစ္စည်း အချက်အလက် ကို သိမ်းဆည်းရန်', 'slug' => 'attributes-store'],
//         ['name_en' => 'Product Attribute Edit', 'name_mm' => 'ကုန်ပစ္စည်း အချက်အလက် ကို ပြုပြင်ရန်', 'slug' => 'attributes-edit'],
//         ['name_en' => 'Product Attribute Show', 'name_mm' => 'ကုန်ပစ္စည်း အချက်အလက် ကို ကြည့်ရန်', 'slug' => 'attributes-show'],
//         ['name_en' => 'Product Attribute Update', 'name_mm' => 'ကုန်ပစ္စည်း အချက်အလက် ကို ပြန်လည် သိမ်းဆည်းရန်', 'slug' => 'attributes-update'],
//         ['name_en' => 'Product Attribute Destroy', 'name_mm' => 'ကုန်ပစ္စည်း အချက်အလက် ကို ဖြတ်သိမ်းရန်', 'slug' => 'attributes-destroy'],
//         ['name_en' => 'Product Attribute To Trash', 'name_mm' => 'ကုန်ပစ္စည်း အချက်အလက် ကို ခဏ ဖြတ်သိမ်းရန်', 'slug' => 'attributes-to-trash'],
//         ['name_en' => 'Product Attribute Trashed List', 'name_mm' => 'ကုန်ပစ္စည်း အချက်အလက် ကို ခဏ ဖြတ်သိမ်းစရင်း', 'slug' => 'attributes-trashed'],
//         ['name_en' => 'Product Attribute Restore', 'name_mm' => 'ကုန်ပစ္စည်း အချက်အလက် ကို ခဏ ဖြတ်သိမ်းရာမှာ ပြန်ယူရန်', 'slug' => 'attributes-restore'],
//         ['name_en' => 'Product Attribute Restore All', 'name_mm' => 'ကုန်ပစ္စည်း အချက်အလက်များ ကို ခဏ ဖြတ်သိမ်းရာမှာ ပြန်ယူရန်', 'slug' => 'attributes-restore-all'],
//     ],
// ];
